name: news
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.4
  
  # build_runner: ^2.4.6         # 最新稳定版本
  # auto_route_generator: ^7.3.1 # 如果你用 auto_route
  # json_serializable: ^6.7.1   

  # 加密安全 SHA
  crypto: ^3.0.3

  # 通讯 http
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0

  # storage + cache
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3

  # 状态管理
  provider: 6.1.1
  
  # 上下拉刷新
  easy_refresh: ^3.4.0
  # 骨架屏 替换之前的pk_skeleton
  shimmer: ^3.0.0
  # skeletons: ^0.0.3
  # 路由管理
  auto_route: ^10.1.0+1
  # 日期格式
  intl: ^0.19.0
  # webview
  webview_flutter: ^4.13.0
  share_plus: ^7.0.0
  loading_animations: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # 路由生成
  auto_route_generator: ^10.1.0
  build_runner: ^2.4.15
 
  


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Avenir
    fonts:
      - asset: assets/fonts/Avenir-Book.ttf
        weight: 400
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
  - family: Iconfont
    fonts:
      - asset: assets/fonts/iconfont.ttf  


  
