name: flutter_news
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.4
  
  # build_runner: ^2.4.6         # 最新稳定版本
  # auto_route_generator: ^7.3.1 # 如果你用 auto_route
  # json_serializable: ^6.7.1   

  # 加密安全 SHA
  crypto: ^3.0.3

  # 通讯 http
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.0

  # storage + cache
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3

  # 状态管理
  provider: 6.1.1
  
  # 上下拉刷新
  easy_refresh: ^3.4.0
  # 骨架屏 替换之前的pk_skeleton
  shimmer: ^3.0.0
  # skeletons: ^0.0.3
  
  # 路由管理
  auto_route: ^7.8.4
   # 日期格式
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
  - family: Avenir
    fonts:
      - asset: assets/fonts/Avenir-Book.ttf
        weight: 400
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
  - family: Iconfont
    fonts:
      - asset: assets/fonts/iconfont.ttf  

  
